---
# Purpose: Prepare the Python environment for backend services
- name: install python packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.9  # Ensures we use the correct version for RHEL 9